name: Workflow Command

on: workflow_dispatch

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
          echo "::group::My title"
          echo "Inside group"
          echo "::endgroup::"
          echo "::add-mask::Mona The Octocat"
